### ISSUE TITLE
KeyError: "Column(s) ['GPUMemoryUtilization', 'GPUUtilization'] do not exist" for non-GPU instances

### ISSUE THREAD

**Issue by jimburtoft** [aws-samples/foundation-model-benchmarking-tool#111]
I tried to benchmark two inf2 instances against teach other.  

I got the error KeyError: "Column(s) ['GPUMemoryUtilization', 'GPUUtilization'] do not exist"

error excerpt and config file attached.  

However, it does work for configs/llama2/7b/config-llama2-7b-inf2-g5.yml

I think this is because the g5 instance does have those values, so the GPU columns exist in the dataframe.
[error log excerpt.txt](https://github.com/user-attachments/files/15686567/error.log.excerpt.txt)
[Inf2-TGIvLMI.txt](https://github.com/user-attachments/files/15686576/Inf2-TGIvLMI.txt)

**Comment by jimburtoft** [comment]
I confirmed it.  If I add the configuration for a g5 onto the end of my config file, everything works.

**Comment by aarora79** [comment]
ACK. Will fix this.

**Comment by aarora79** [comment]
this is fixed as of v1.0.47.

**Comment by harmeet-singh-discovery** [comment]
Any ETA on this?

**Comment by harmeet-singh-discovery** [comment]
I am getting the error:
```
KeyError: "Column(s) ['GPUMemoryUtilization', 'GPUUtilization'] do not exist"
```

I am using `ml.inf2.48xlarge` machines to run benchmark.
