### ISSUE TITLE
Support Python 3.10 for SageMaker Studio notebooks

### ISSUE THREAD

**Issue by athewsey** [aws-samples/foundation-model-benchmarking-tool#94]
Hi team,

Since FMBench today [requires](https://github.com/aws-samples/foundation-model-benchmarking-tool/blob/4adc5b65c2a7b3164e6e260496cbed90b9a3effa/pyproject.toml#L12) Python 3.11+, it can't be installed on the current SageMaker Studio JupyterLab (default Python kernel at SM Distribution v1.7 runs Python 3.10)

Are you really using [newly launched features in Python 3.11](https://docs.python.org/3.14/whatsnew/3.11.html)? Would you be able to add 3.10 support so we can use the library in SageMaker Studio notebooks?

Thanks!

**Comment by antara678** [comment]
addressed and fixed on branch python-3.10
